GET https://sih-ccm-2020.herokuapp.com


### Check Server Status


GET https://sih-ccm-2020.herokuapp.com/api


### Login
POST https://sih-ccm-2020.herokuapp.com/api/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin123"
}


###