GET http://localhost:5000


### Check Server Status


GET http://localhost:5000/api


### Login
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "password"
}


### Get all Clients
GET http://localhost:5000/api/clients


### Get lawyer by id
GET http://localhost:5000/api/clients/client-in3Fl0vu1p6fmqWocE8r2fxNpb2Eg1o5


### Add Client
POST http://localhost:5000/api/clients
Content-Type: application/json

{
    "email": "ejekanshjain@gmail.com",
    "name": "Ekansh Jain",
    "phoneNumber": 9530077351,
    "aadharNumber": 123456789012
}


### Get all lawyers
GET http://localhost:5000/api/lawyers


### Get lawyer by id
GET http://localhost:5000/api/lawyers/lawyer-vau2naXRtxJ6X0jnbq74MX5I9CEDCBTi


### Add Lawyer
POST http://localhost:5000/api/lawyers
Content-Type: application/json

{
    "email": "nayan94621@gmail.com",
    "name": "Nayan Sharma",
    "phoneNumber": 9079512345,
    "aadharNumber": 123456789012,
    "license": 12345678
}


### Add case
POST http://localhost:5000/api/cases
Content-Type: application/json

{
    "fileId": "fp30f99v",
    "type": "murder",
    "lawyerId": "lawyer-6969",
    "clientId": "client-in3Fl0vu1p6fmqWocE8r2fxNpb2Eg1o5"
}


###
